version: '2'

services:
    master:
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=passwd
        networks:
            mysql_net:
                ipv4_address: 172.16.242.2
        volumes:
            - ./master/conf.d:/etc/mysql/conf.d
            - ./master/init:/docker-entrypoint-initdb.d/
    slave:
        image: mysql:5.7
        depends_on:
            - master
        environment:
            - MYSQL_ROOT_PASSWORD=passwd
        volumes:
            - ./slave/conf.d:/etc/mysql/conf.d
            - ./slave/init:/docker-entrypoint-initdb.d/
        networks:
            mysql_net:
                ipv4_address: 172.16.242.3
    
networks:
    mysql_net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.16.242.0/24
                  gateway: 172.16.242.1
